In [1]:
import numpy as np

In [2]:
# creating numpy array 
array = np.array([1,2,3])
array

array([1, 2, 3])

In [3]:
array * 10

array([10, 20, 30])

In [6]:
#multi dimensional arrays 

#at first 0 dimensional array
zero_array = np.array('A')
zero_array.ndim

0

In [8]:
# 1 dimensional array 
array = np.array([1,2,3])
array.ndim

1

In [ ]:
# 2 dimensional array 
two_array = np.array([[1,2,3], 
                      [4,5,6]])
two_array.ndim

2

In [21]:
# 3D array
three_array = np.array([[[1,2,3],[4,5,6],[7,8,9]], 
                        [['a', 'b', 'c'], ['a', 'b', 'c'], ['a', 'b', 'c']], 
                        [['D', 'E', 'F'], ['G', 'H', 'I'], ['J', 'K', 'L']]])
three_array

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']],

       [['a', 'b', 'c'],
        ['a', 'b', 'c'],
        ['a', 'b', 'c']],

       [['D', 'E', 'F'],
        ['G', 'H', 'I'],
        ['J', 'K', 'L']]], dtype='<U21')

In [15]:
three_array.shape

(3, 3, 3)

In [23]:
three_array[2][0][0]

np.str_('D')

In [25]:
word = three_array[2][0][0] + three_array[2][0][1] + three_array[2][0][2]
word

'DEF'

In [ ]:
# slicing 
arr = np.array([[1,2,3,4],
                 [5,6,7,8], 
                 [9,10,11,12], 
                 [13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
arr[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [35]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
#select column 
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [40]:
#scalar arithmetic
arr * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [41]:
arr + 100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112],
       [113, 114, 115, 116]])

In [42]:
arr - 100

array([[-99, -98, -97, -96],
       [-95, -94, -93, -92],
       [-91, -90, -89, -88],
       [-87, -86, -85, -84]])

In [43]:
arr / 34

array([[0.02941176, 0.05882353, 0.08823529, 0.11764706],
       [0.14705882, 0.17647059, 0.20588235, 0.23529412],
       [0.26470588, 0.29411765, 0.32352941, 0.35294118],
       [0.38235294, 0.41176471, 0.44117647, 0.47058824]])

In [46]:
arr ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [48]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
#vecrtorized math funcstions
sarr = np.sqrt(arr)
sarr

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [51]:
np.round(sarr)

array([[1., 1., 2., 2.],
       [2., 2., 3., 3.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [54]:
radii = np.array([1,2,3])
area = (radii**2) * np.pi
area

array([ 3.14159265, 12.56637061, 28.27433388])

In [55]:
np.array([1,2,3]) + np.array([10,10,10])

array([11, 12, 13])

In [56]:
np.array([7, 8, 11]) - np.array([5, 3, 2])

array([2, 5, 9])

In [57]:
np.array([7, 8, 11]) * np.array([5, 3, 2])

array([35, 24, 22])

In [58]:
np.array([14, 16, 33]) / np.array([7, 8, 11])

array([2., 2., 3.])

In [ ]:
#comparison operators 

In [60]:
scores = np.array([23,91,81, 100, 55, 67, 96])
print(scores == 100)

[False False False  True False False False]


In [62]:
print(scores > 70)

[False  True  True  True False False  True]


In [63]:
scores[scores < 60] = 0 
print(scores)

[  0  91  81 100   0  67  96]


In [65]:
#broadcasting 
array1 = np.array([[12,345,456,567]])
array2 = np.array([[1], [2], [3], [4]])
print(array1.shape, array2.shape)

(1, 4) (4, 1)


In [66]:
print(array2 * array1)

[[  12  345  456  567]
 [  24  690  912 1134]
 [  36 1035 1368 1701]
 [  48 1380 1824 2268]]


In [68]:
array3 = np.array([[1,2,3,4,5,6,7,8,9]])
array4 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
print(array3.shape)
print(array4.shape)

(1, 9)
(9, 1)


In [69]:
print(array3*array4)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [78]:
arr = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr, axis=1))
print(arr)

30
3.0
1.4142135623730951
[15 15]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [87]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])
teens = ages[ages < 18]
print(teens)
uncs = ages[((ages > 30) & (ages < 50)) | (ages<4)]

print(uncs)


[17 16 15]
[39]


In [ ]:
adults = np.where(ages >= 18, ages, np.nan)
adults

array([[21., nan, 19., 20., nan, 30., 18., 65.],
       [39., 22., nan, 99., 18., 19., 20., 21.]])

In [ ]:
#random numbers
rng = np.random.default_rng() # random generator 
print(rng.integers(low=1,high=6+1, size=(3,2))) #3 rows 2 columns

[[4 3]
 [1 6]
 [6 3]]
